Repository oneirism/reverie, pull requests merged in 2018-12, with the labels that each got.

#72 #67: fix W605 in account urls
  account/urls.py
Labels: Type: Bug

#76 Implement Avatars
  Pipfile
  Pipfile.lock
  assets/src/css/image_cropping.css
  assets/src/css/jquery.Jcrop.css
  assets/src/images/Jcrop.gif
  assets/src/index.js
  assets/src/intermediate-sass/main.css
  assets/src/js/image_cropping.js
  assets/src/js/jquery.Jcrop.js
  assets/src/sass/images.scss
  assets/src/sass/main.scss
  campaign/admin.py
  campaign/forms.py
  campaign/helpers.py
  campaign/models.py
  campaign/templates/campaign/campaign_detail.html
  campaign/templates/campaign/campaign_form.html
  campaign/templates/campaign/character_detail.html
  campaign/templates/campaign/character_form.html
  campaign/templates/campaign/faction_detail.html
  campaign/templates/campaign/faction_form.html
  campaign/templates/campaign/item_detail.html
  campaign/templates/campaign/item_form.html
  campaign/templates/campaign/location_detail.html
  campaign/templates/campaign/location_form.html
  campaign/templates/campaign/log_detail.html
  campaign/templates/campaign/log_form.html
  campaign/test/test_helpers.py
  campaign/views.py
  reverie/settings/base.py
  reverie/urls.py
  webpack.config.js
Labels: Priority: High, Status: In Progress, Type: Feature

#80 Zappa
  .gitignore
  .travis.yml
  Pipfile
  Pipfile.lock
  account/templates/mfa/setup_complete.html
  campaign/test/test_campaign_ownership.py
  campaign/test/test_views.py
  campaign/views.py
  deploy.sh
  reverie/settings/base.py
  reverie/settings/deploy.py
  reverie/settings/local.py
  reverie/settings/staging.py
  reverie/urls.py
  secure/prod.py.enc
  splash/test/test_index.py
  templates/base.html
  webpack.config.js
  zappa_settings.json
Labels: Priority: High, Type: Feature
